version: '2'
services:
  ui:
    build: .
    ports:
      - "3001:80"
    volumes:
      - .:/usr/src/testkittui
    environment:
      - NODE_ENV=development
      - PORT=80
      - MONGO_HOST=mongo
    depends_on:
      - mongo
  mongo:
    image: "mongo:latest"